app/questions/urls.py
from django.urls import path

from .views import (
    QuestionsView,
    QuestionDetailsView,
)

app_name = 'questions'


urlpatterns = [
    path(
        '',
        QuestionsView.as_view(),
        name='questions',
    ),
    path(
        '<int:pk>',
        QuestionDetailsView.as_view(),
        name='questions',
    ),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django_js_reverse.views import urls_js
from app.accounts.views import HomeView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('jsreverse/', urls_js, name='js_reverse'),
    path('api/', include('app.api.urls')),
    path('questions/', include('app.questions.urls')),
    path('', HomeView.as_view(), name='home'), # this must be at the bottom
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from .managers import AccountManager


class Account(AbstractUser):
    username = None
    email = models.EmailField(
        verbose_name='email address',
        max_length=255,
        unique=True,
    )

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = AccountManager()

app/associates/models.py
from django.db import models

from app.core.models import BaseModel
# from app.questions.models import (
#     Tag,
# )


# class QuestionTag(BaseModel):
#     question_id = models.ForeignKey(
#         Question,
#         on_delete=modles.CASCADE,
#     )

#     tag_id = models.ForeignKey(
#         Tag,
#         on_delete=models.CASCADE,
#     )

app/core/models.py
from django.conf import settings
from django.db import models


# Create your models here.
class BaseModel(models.Model):
    """
    Base abstract model that provides common fields
    Inherited by all of the app models

    @field
    is_active : deactivating instead of delete the record
    """
    created_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='+',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    modified_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='+',
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    is_active = models.BooleanField(default=True)

    class Meta:
        abstract = True

app/questions/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

from app.core.models import BaseModel


class Question(BaseModel):
    title = models.CharField(max_length=100)
    content = models.TextField()
    tags = models.ManyToManyField(
        'questions.Tag',
        related_name='questions',
    )
    accepted_answer = models.ForeignKey(
        'questions.Answer',
        on_delete=models.SET_NULL,
        related_name='answer_to_question',
        null=True,
    )

    # stackoverflow imported fields
    creator_name = models.CharField(
        max_length=100,
        blank=True,
        default='',
        help_text='This is only for imported data',
    )

    def __str__(self):
        return self.title


class Answer(BaseModel):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.TextField()

    # stackoverflow imported fields
    creator_name = models.CharField(
        max_length=100,
        blank=True,
        default='',
        help_text='This is only for imported data',
    )

    def __str__(self):
        return self.answer[:75]


class Comment(BaseModel):
    text = models.TextField()

    # dynamic foreign key
    # https://docs.djangoproject.com/en/dev/ref/contrib/contenttypes/#generic-relations
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return self.text


class Tag(BaseModel):
    name = models.CharField(max_length=64)

    def __str__(self):
        return self.name

app/accounts/views.py
from django.shortcuts import render
from app.core.views import GenericView
# Create your views here.


class HomeView(GenericView):
    template_name = 'accounts/home.html'

app/api/views/questions.py
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.generics import (
    ListAPIView,
    ListCreateAPIView,
    RetrieveUpdateAPIView,
)
# from django_filters.rest_framework import DjangoFilterBackend

from app.questions.models import (
    Question,
)

from ..serializers.questions import (
    QuestionSerializer,
)


class QuestionListCreateAPIView(ListCreateAPIView):
    serializer_class = QuestionSerializer
    filter_backends = (
        SearchFilter,
        OrderingFilter,
    )
    search_fields = (
        'title',
        'content',
        'tags__name',
    )
    ordering_fields = (
        'title',
        'created_time',
        'modified_time',
    )

    def get_queryset(self, **kwargs):
        qs = Question.objects.all()
        tags = self.request.query_params.get('tags[]')
        if tags:
            qs = qs.filter(
                tags__id__in=tags,
            )
        return qs

app/associates/views.py
from django.shortcuts import render

# Create your views here.

app/core/views.py
from django.shortcuts import render
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.


class GenericView(View):
    """
    Base view that every view should inherit from.
    Adds a default `user` instance to the context data
    """
    template_name = 'base.html'

    def get_context_data(self, **kwargs):
        context = {}
        context.update(**kwargs)
        return context

    def get(self, request, *args,  **kwargs):
        context = self.get_context_data(**kwargs)
        return render(request, self.template_name, context)


class LoginGenericView(LoginRequiredMixin, GenericView):
    """
    Any core view that requires a login redirect should inherit from.
    """
    login_url = 'account_login'

app/questions/views.py
from app.core.views import GenericView


class QuestionsView(GenericView):
    template_name = 'questions/index.html'


class QuestionDetailsView(GenericView):
    template_name = 'questions/details.html'
    pk_url_kwarg = 'pk'

app/templates/accounts/home.html
{% extends 'base.html' %}
{% load static %}
{% load render_bundle from webpack_loader %}

{% block title %}
Ask meow
{% endblock %}

{% block content %}
<div id="app-home"
     data-user-id="{{ user.id }}">
</div>
{% endblock content %}

{% block scripts %}
{% render_bundle 'home' %}
{% endblock %}

app/templates/base.html
{% load static %}
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html lang="en-us">

<head>

  {# Meta Section #}
  {% include 'common/metas.html' %}
  {% block head_meta %}
  {% endblock head_meta %}

  <title>
    {% block title %}
    Ask meow
    {% endblock title %}
  </title>

  <link rel="icon" type="image/png" sizes="32x32" href="/assets/img/askmeow.png">

  {# Fonts Section #}
  {% include 'common/fonts.html' %}
  {% block head_fonts %}
  {% endblock head_fonts %}

  {# Styles Section #}
  {% include 'common/styles.html' %}
  {% block head_styles %}
  {% endblock head_styles %}

  {# Django JS Reverse #}
  {% comment %}
  Put this here so that it will be accessible already for the Vue components
  {% endcomment %}
  <script src="{% url 'js_reverse' %}" type="text/javascript"></script>

</head>

{% block body_tag %}
<body>
{% endblock %}

  {% block body %}
  {% block header %}
  {% include 'common/header.html' %}
  {% endblock header %}

  {% block wrapper %}
  <div id="main-content" class="wrapper">
    {% block content %}
    {% endblock content %}
  </div>
  {% endblock wrapper %}

  {% block footer %}
  {% include 'common/footer.html' %}
  {% endblock footer %}

  {# JS Section #}
  {% include 'common/scripts.html' %}
  {% block scripts %}
  {% endblock scripts %}

  {# Quick and dirty on page JS Section #}
  {% block page_scripts %}
  {% endblock page_scripts %}

</body>
{% endblock body %}

</html>

app/templates/common/fonts.html
{% load static %}

{# Font awesome #}
<link rel="stylesheet" type="text/css" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
<link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,500;0,700;0,800;1,400;1,500;1,700;1,800&display=swap" rel="stylesheet">

app/templates/common/footer.html
<footer>
</footer>

app/templates/common/header.html
{% load static %}

<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <img src="/assets/img/askmeow.png" width="30" height="30" class="d-inline-block align-top" alt="">
      Ask meow
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <form id="main-search" class="d-flex mr-5" method="GET" action="{% url 'questions:questions' %}">
        <input class="form-control mr-2" type="search" placeholder="Search" aria-label="Search" name="search" />
        <button class="btn btn-outline-secondary" type="submit">
          Search
        </button>
      </form>
      {% if user.is_authenticated %}
      <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
        <!-- change this to user icon + dropdown -->
        <li class="nav-item mr-2">
          <a class="btn btn-outline-secondary" href="/accounts/logout/" style="width: 95px;">Sign out</a>
        </li>
      </ul>
      {% else %}
      <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
        <li class="nav-item mr-2">
          <a class="btn btn-primary" href="/accounts/login/">Login</a>
        </li>
        <li class="nav-item">
          <a class="btn btn-outline-primary" href="/accounts/signup/">Signup</a>
        </li>
      </ul>
      {% endif %}
    </div>
  </div>
</nav>

app/templates/common/metas.html
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

app/templates/common/scripts.html
{% load static %}
{# Third party scripts #}
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
  integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/js/bootstrap.min.js"
  integrity="sha384-5h4UG+6GOuV9qXh6HqOLwZMY4mnLPraeTrjT5v07o347pj6IkfuoASuGBhfDsp3d" crossorigin="anonymous"></script>

{# Global Promise Object if the browser doesn't have window.Promise #}
<script src="https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.min.js"></script>

{# Custom #}
<script>
</script>

app/templates/common/styles.html
{% load static %}

{# Bootstrap #}

{# Local Asset #}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha2/css/bootstrap.min.css"
  integrity="sha384-DhY6onE6f3zzKbjUPRc2hOzGAdEf4/Dz+WJwBvEYL/lkkIsI3ihufq9hk9K4lVoK" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
<style>
</style>

app/templates/questions/details.html
{% extends 'base.html' %}
{% load static %}
{% load render_bundle from webpack_loader %}

{% block title %}
Ask meow
{% endblock %}

{% block content %}
<div id="app-question-details"
     data-question-id="{{ pk }}"
     data-user-id="{{ user.id }}">
</div>
{% endblock content %}

{% block scripts %}
{% render_bundle 'question_details' %}
{% endblock %}

app/templates/questions/index.html
{% extends 'base.html' %}
{% load static %}
{% load render_bundle from webpack_loader %}

{% block title %}
Ask meow
{% endblock %}

{% block content %}
<div id="app-questions"
     data-user-id="{{ user.id }}">
</div>
{% endblock content %}

{% block scripts %}
{% render_bundle 'questions' %}
{% endblock %}

app/templates/sample.html
{% extends 'base.html' %}
{% load static %}
{% load render_bundle from webpack_loader %}

{% block title %}
{{ supplier.name }}
{% endblock %}

{% block content %}
<div id="app"
     data-some-id="{{ pk }}">
</div>
{% endblock content %}

{% block scripts %}
{% render_bundle 'app_name' %}
{% endblock %}